#! /bin/bash

RES_WIDTH=1920

NUM_OF_DESKTOPS=$(xrandr | awk '$2 == "connected"{print $1}' | wc -l)

if [[ $NUM_OF_DESKTOPS -eq 2 ]]; then
    xrandr --output HDMI-A-0 --mode 1920x1080 --primary --output DisplayPort-2 --mode 1920x1080 --right-of HDMI-A-0

    bspc monitor HDMI-A-0 -d I II III IV V VI VII VIII IX X
    bspc monitor DisplayPort-2 -d XI XII XIII XIV XV XVI XVII XVIII XIX XX 
elif [[ $NUM_OF_DESKTOPS -eq 3 ]]; then
    xrandr --output HDMI-A-0 --mode 1920x1080 --primary --output DisplayPort-2 --mode 1920x1080 --right-of HDMI-A-0 --output DVI-D-0 --mode 1920x1080 --left-of HDMI-A-0

    bspc monitor DVI-D-0 -d I II III IV V 
    bspc monitor HDMI-A-0 -d VI VII VIII IX X
    bspc monitor DisplayPort-2 -d XI XII XIII XIV XV
else
    bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
fi

sxhkd &

bspc config window_gap 16

# Set the border colors.
bspc config border_width 4

bspc config top_padding 45
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false

bspc config external_rules_command /home/jp/.config/bspwm/external_rules.sh

## AutoStart
setBackground &
compton &
menu_bar &
